version: 0.2

env:
  variables:
    # This S3 stores the ECS Reference Architecture CloudFormation templates
    # so that they can be deployed via a button on the project GitHub README
    S3_BUCKET: "max-springbootdocker"

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd ..
      - ./mvnw clean install
      - ./mvnw dockerfile:build
      - docker tag gs-spring-boot-docker:latest 015411923805.dkr.ecr.us-east-1.amazonaws.com/gs-spring-boot-docker
      # Sync the templates
      # - aws s3 sync . s3://${S3_BUCKET}
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 015411923805.dkr.ecr.us-east-1.amazonaws.com/gs-spring-boot-docker/nodeserver:latest
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1)

